spring.application.name=Library-Management-System

server.port=5050

logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/librarymsdb
spring.datasource.username=database_username
spring.datasource.password=database_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5050
spring.mail.properties.mail.smtp.writetimeout=5050


razorpay.key.id=your_razorpayKeyId
razorpay.key.secret=your_razorpayKeySecret
razorpay.callback.base-url=http://localhost:5173
